// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iywrcosymxjynxspzjmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5d3Jjb3N5bXhqeW54c3B6am1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMDM1NjksImV4cCI6MjA3Mzg3OTU2OX0.4vAHFMTGs0oz3zmAq1WvhaJhwm_rhxc7NuBqE_Z0_lE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});